### ISSUE TITLE
Import dataset error: Pandas (installed) not found

### ISSUE THREAD

**Issue by UboCA** [tanaylab/MCView#130]
Hi, tanaylab team,

MCView should be very useful for data exploration. But in my first run I got a module error:
![image](https://user-images.githubusercontent.com/69028068/219851050-e9e658c1-a8ef-4d2d-b662-d0ecc2ef7a97.png)

Strangely, I checked pandas by conda list, it is there.
Could you tell me why doesn't MCView link pandas installed?

**Comment by aviezerl** [comment]
Hi @UboCA, 

MCView uses [anndata](https://github.com/dynverse/anndata) to read the h5ad file. Can you try running: 

```r
library(anndata) 
anndata::read_h5ad("raw/metacells.h5ad")
```

And see if you get the same error? If so (which is probably the case), I suggest posting this issue on https://github.com/dynverse/anndata/issues

Please update if the issue wasn't fixed. 

Aviezer

**Comment by UboCA** [comment]
> Hi @UboCA,
> 
> MCView uses [anndata](https://github.com/dynverse/anndata) to read the h5ad file. Can you try running:
> 
> ```r
> library(anndata) 
> anndata::read_h5ad("raw/metacells.h5ad")
> ```
> 
> And see if you get the same error? If so (which is probably the case), I suggest posting this issue on https://github.com/dynverse/anndata/issues
> 
> Please update if the issue wasn't fixed.
> 
> Aviezer
Thanks~You are right, that error is from anndata. I will re-open it on anndata.
