### ISSUE TITLE
Enrichment score in MCView

### ISSUE THREAD

**Issue by UboCA** [tanaylab/MCView#131]
Hi,

I wonder how MCView calculate **gene expression & enrichment score** in one metacell.
![image](https://user-images.githubusercontent.com/69028068/220818830-506fe8f5-982a-43e7-a6b5-7723c83f8d80.png)
Could `log_fractions` in the following code explain the calculating process of **gene expression**?
```R
mdata <- anndata::read_h5ad('metacells.h5ad')
umis <- as.matrix(mdata$X)
fractions <- umis / rowSums(umis)
log_fractions <- log2(1e-5 + fractions)
```
If so, what about enrichment score?

**Comment by aviezerl** [comment]
Yes `log_fractions` in your code represents the gene expression. Enrichment the fold change above the median of each gene. So in your code: 

```r
enrichment <- t(t(log_fractions) / apply(t(log_fractions), 1, median, na.rm = TRUE))
```

**Comment by UboCA** [comment]
Thanks for your detailed reply.

Best
