### ISSUE TITLE
Error in run_app

### ISSUE THREAD

**Issue by SalimMegat** [tanaylab/MCView#149]
Hi, 

I am getting an error any time I run_app in Rstudio (MCView version 0.2.20): 

Warning: Error in mutate: Problem while computing `cell_type = as.character(forcats::fct_na_value_to_level(cell_type, "(Missing)"))`.
Caused by error:
! 'fct_na_value_to_level' is not an exported object from 'namespace:forcats'

**Comment by aviezerl** [comment]
Hi @SalimMegat,

What is the version of your `forcats` package? 

```r
packageVersion("forcats")
```

`forcats::fct_na_value_to_level` was introduced only in version 1.0.0, which is the reason forcats >= 1.0.0 is required at the DESCRIPTION file.
