### ISSUE TITLE
[0.2.24] can't installed because of missing tgutil (>= 0.1.11)

### ISSUE THREAD

**Issue by tuxmaster5000** [tanaylab/MCView#156]
0.1.4 will be the last version
https://github.com/tanaylab/tgutil/tags

**Comment by aviezerl** [comment]
The current version is 0.1.15 and can be installed using: 

```r
remotes::install_github("tanaylab/tgutil")
```

Indeed the latest tag was 0.1.4. This was changed - thank you very much for pointing it out!
