### ISSUE TITLE
Issue with Importing PBMC Demo Data into MCView

### ISSUE THREAD

**Issue by UboCA** [tanaylab/MCView#163]
Dear MCView Development Team,

I am currently experiencing an issue when trying to import the PBMC demo data into MCView. The error message that appears is 'import_dataset Error: Expected a python object, received a character'.

I have attached a screenshot of the error message for your reference:
![image](https://github.com/tanaylab/MCView/assets/69028068/4d89c859-9738-4d64-bb21-294c9958bc10)

Here are the details of my current environment:
"""
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/godusevpn/miniconda310/envs/mcview/lib/libopenblasp-r0.3.27.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base 
"""

Notably, the same issue arises when I attempt to import my own data.
I would greatly appreciate any guidance or suggestions on how to troubleshoot and resolve this issue. 

Best regards,

UboCA

**Comment by UboCA** [comment]
I also tried loading an AnnData object, but unfortunately, I encountered the same issue.
![image](https://github.com/tanaylab/MCView/assets/69028068/22237459-223e-41e9-ac2e-298b798be52d)
`anndata_file` requires `path to ‘h5ad’ file which contains the output of metacell2 pipeline (metacells python package) or a loaded anndata object of the same format`.

**Comment by UboCA** [comment]
@orenbenkiki @aviezerl @drorbar @actions-user 
I have another issue on importing dataset into MCView.
![image](https://github.com/tanaylab/MCView/assets/69028068/eee71d5c-8450-498d-869b-df4039a8b4fb)

In the PBMC demo data, there is a 'var' field named either 'top_feature_gene' or 'feature_gene'. 

However, when I process my data using the Metacells 0.9.4 pipeline, this 'var' field does not appear in the output.

I would like to understand which step in the process is responsible for generating this 'var' field. 

Thanks for any help about this problem.

**Comment by orenbenkiki** [comment]
> In the PBMC demo data, there is a 'var' field named either 'top_feature_gene' or 'feature_gene'.

This turned out not to be as useful as you'd think. The best way to look for "meaningful" genes (that vary between metacells) is to look at `marker_gene`. The README at https://github.com/tanaylab/metacells lists all the properties you get in the 0.9.* versions.
