### ISSUE TITLE
Miss "# of metacells with significant inner-fold"

### ISSUE THREAD

**Issue by UboCA** [tanaylab/MCView#164]
Hi, 

As described in [iterative jupyter notebook](https://github.com/tanaylab/metacells-vignettes/blob/main/notebooks/iterative.ipynb), `# of metacells with significant inner-fold` is possibly useful for metacell downstream analysis. However, I could not find it in my current MCView framework (MCView 0.2.28 | metacells.0.9.4), but only an inner-fold heatmap. 
![image](https://github.com/tanaylab/MCView/assets/69028068/cedb34ef-d070-4be0-87e5-820177bbedb3)

Was there any omission in my operation, or was this part removed during the software update process?

I would greatly appreciate it if you could provide some guidance on this issue.

Best,

UboCA

**Comment by aviezerl** [comment]
You can find the # of metacells with significant inner-fold at the QC tab: 

![image](https://github.com/tanaylab/MCView/assets/18175550/62898d00-a529-42c9-ac4d-fb361863216d)

Aviezer

**Comment by UboCA** [comment]
Ok, nice of you!
