### ISSUE TITLE
Trying to highlight selected mc in annotation tab doiesn't work and freezes 

### ISSUE THREAD

**Issue by drorbar** [tanaylab/MCView#20]
In the "Metacells" tab when choosing metacell we get a circle around it. On the other hand when doing the same on the "annotation" tab we don't see this

**Comment by drorbar** [comment]
Also, it seems that when choosing a mc in the gg_plot under "annotation tab" the screen freezes and we get the error “Error in if: argument is of length zero”.
This requires refreshing the page to continue working

**Comment by aviezerl** [comment]
Fixed.
