### ISSUE TITLE
filtering out cell types should not refreshed after annotation

### ISSUE THREAD

**Issue by drorbar** [tanaylab/MCView#35]
When you press cell types in the annotation screen, they are filtered out.
After changing annotation, all the cells types are shown again, requiring the user to do all the processes again.
If the user doesn't return those cells, or hit refresh on the entire page - those filtering should stay even after the annotation

**Comment by aviezerl** [comment]
Good idea, but I am afraid this would be non-trivial to implement. The visibility of those plot is controlled by plotly, so we would have to keep track of the last plotly restyle event and apply it on re-rendering. Possible, but might be a bit tricky. 

Aviezer

**Comment by drorbar** [comment]
That's odd, once I filter one cell type and then another the code still remembers the first cell type I've changed. Do you say that this isn't saved anywhere ? 
Why is this different than saving the size of the points?

**Comment by aviezerl** [comment]
It is saved at the plotly level and not shiny reactive values. It is different from the size of points since the visibility of cell types is controlled by plotly and not by us (through ggplot).
