### ISSUE TITLE
cell type should stay after annotation

### ISSUE THREAD

**Issue by drorbar** [tanaylab/MCView#36]
currently, after changing cell type (doing annotation), the cell type return to "missing".
I think it makes more sense to keep it the same cell type we changed last

**Comment by aviezerl** [comment]
Just to clarify - you probably mean that the cell type selector returns to "(missing)" instead of remembering the last selected type. Good idea to implement it indeed.

**Comment by drorbar** [comment]
yeah that exactly what I mean
