### ISSUE TITLE
Inconsistancy in filtering cell type in annotation page

### ISSUE THREAD

**Issue by drorbar** [tanaylab/MCView#41]
At least, I think it's a bug.
If you go to the annotation page, and you filter out a cell type (by clicking on the gene projections legend), this cell type will disappear from the manifold and from the gene-gene plot -> this makes sense.
If now you choose a group of cells and change their annotation the filtering reset -> this was talked here: "https://github.com/tanaylab/MCView/issues/36"
On the other hand, if you change the chosen genes, those cells will reappear in the gene-gene plot but not in the gene projection. To remove those cell types in the gene-gene plot, you need to return them in the manifold and then filter them out again.
I guess this is happening because those two graphs aren't strongly linked in the objects they show, but the fact that when originally filtering out, they are connected, but after a change, they sometimes are and sometimes aren't is a bit weird .

**Comment by aviezerl** [comment]
The coupling of the gene/gene plot and the projection plots is done using plotly events, and indeed it is not connected to the general shiny dependency structure, see: 

https://github.com/tanaylab/MCView/blob/192d6f06692a0b4f875fad0f936104d3924c628a/R/plot_gene_mc.R#L132

I do not know an easy way to identify that the visibility state of the projection has changed, so I fixed it by artificially connect ing the projection and the gene plot using shiny reactivity. Note that this means that the projection plot would be re-rendered any time the gene is changed.
